### ISSUE TITLE
Team Name

### ISSUE THREAD

**Issue by bink** [od0x0/7dfps#1]
We really need a proper name before we start.
Suggestions go in the comments.

**Comment by od0x0** [comment]
I liked "Team Comic Sans"

**Comment by bink** [comment]
I guess that would work, but I'm not too happy with it. Sounds like we're just trolling.

**Comment by trianglebutt** [comment]
I mean we kind of are. But is Comic Sans a trademark? I feel like we need to have something we can use freely.

**Comment by od0x0** [comment]
Ah, yeah, it's trademarked by Microsoft.  We don't want to step on that land mine.  I think a joking name would suit us well, it's probably only a temporary team name, and the game we're trying to make is a joking throwback to Quake/Halo, so it fits.  Joke names are easier to market as well (Not that we're a business or anything...).  I'm fine for any name, really (within reason...).

**Comment by Kurton** [comment]
The Brothers Molotov

**Comment by od0x0** [comment]
Note: Ended up going with PewCubed (Pew^3) because The Brothers Molotov is the name of a bunch of other stuff.  

PewCubed is also the name of a Flash game, but whatever...  no one in their right mind uses Flash (joking irony).

**Comment by trianglebutt** [comment]
whats flash

**Comment by trianglebutt** [comment]
flash gordon?
