### ISSUE TITLE
Writing - Enemy Names

### ISSUE THREAD

**Issue by Kurton** [od0x0/7dfps#12]
Catchy quick monikers for each flavo[u]r of the dear bots

**Comment by Kurton** [comment]
Crawlers, Brawlers, Commanders, Elite Brawlers

**Comment by Kurton** [comment]
Deep-Space Robot Abomination
           - Xebulon -

**Comment by Kurton** [comment]
Clickspits, Chuckspits, Commandspits

**Comment by Kurton** [comment]
Teckspins, Tickspins, Techfliks

**Comment by Kurton** [comment]
Bumpknuts, Rumpknuts

**Comment by Kurton** [comment]
Boltfrags, Burnclaks

**Comment by bink** [comment]
little guys?, Commanders
Exterminators, Super Exterminators
Xebulon

**Comment by trianglebutt** [comment]
+1 for Bumpknuts and Rumpknuts

**Comment by bink** [comment]
imho the names should be a bit more serious, but cheesy. Kind of like in old games. Those names were cheesy and generic as hell but fit the whole thing really well, I think.

**Comment by trianglebutt** [comment]
i agree. i'm going to look up some old game enemy names and see if that inspires any ideas.

**Comment by trianglebutt** [comment]
Quake 2: http://planetquake.gamespy.com/View.php?view=GameInfo.Detail&id=3&game=5
Doom: http://planetdoom.gamespy.com/static.php?page=Classic%20Doom%20Enemies

**Comment by trianglebutt** [comment]
What if we called them like <something> bots. like command bots, security bots something like that.

**Comment by bink** [comment]
Security Bots (little guys)
Command Bots (commanders)
Destroyer Bots (big guys)
Elite Bots (elite big guys)

**Comment by od0x0** [comment]
Pretty straightforward, I like it.  If someone can come up with names that say the same thing, but slightly humorous, it'd be even better.  Unless we're making a _Serious Game For Seriously Manly Men (TM?)_.

**Comment by bink** [comment]
OK. Those are the names for now. Until anyone comes up with something far superior, this issue is closed.

**Comment by trianglebutt** [comment]
Sounds good, I like em
