### ISSUE TITLE
NaGaDeMo - Should We Enter

### ISSUE THREAD

**Issue by od0x0** [od0x0/7dfps#13]
http://nagademo.com/

A contest, June 1st to June 30th, conveniently overlapping with 7dfps.  We may want to continue development on this after 7dfps, so it might make sense to enter this as well.  Preparations may be needed to extend past 7dfps content though.  Creation of further milestones may be necessary.  However, it's important not to lose sight of 7dfps.

Should we join?

**Comment by od0x0** [comment]
Done just to be safe before the deadline.  http://nagademo.com/registry/130

**Comment by Kurton** [comment]
I vote yes

**Comment by bink** [comment]
Why not? Let's focus primarily on 7dfps, and then put in another two weeks to see how it can be improved for NaGaDeMo.
