### ISSUE TITLE
Create a Dev Blog and/or Twitter

### ISSUE THREAD

**Issue by bink** [od0x0/7dfps#2]
There should be a dev blog or a Twitter that we can all access and post stuff to.
Possibly a blog for larger articles (once a day) and a Twitter for random things we have to say about the game.

**Comment by od0x0** [comment]
A full blog might require too much time, as we'll likely be working on content and not have enough time to write articles (I'll have heavy schoolwork as well).  A twitter account might work.

**Comment by bink** [comment]
Once we've all agreed on a name, I'll set up a Twitter then.

**Comment by od0x0** [comment]
As far as the blog, the website says "As the 9th of June approaches, we'll update the site with a public blog for everyone to track progress & share their own!"  So that's covered.

**Comment by trianglebutt** [comment]
i still think we should have a twitter
