### ISSUE TITLE
Audio - Soundtrack/Music

### ISSUE THREAD

**Issue by Kurton** [od0x0/7dfps#31]
Main composers are Kurton and trianglebutt, though really anyone can help out.

So far, need tracks for the following:

-Menu Theme (done)
-Level One
-Level Two
-Boss Fight

As far as I know, it will be sticking to sci-fi themed metal; Heavy guitar riffing with spacious synthesizer and symphonic orchestra elements.

**Comment by od0x0** [comment]
Menu theme is complete, it's in the folder already.
