### ISSUE TITLE
git - Apps in Git?

### ISSUE THREAD

**Issue by bink** [od0x0/7dfps#40]
Should those really be under version controll? The Data folder is probably enough, isn't it?
Then again, they don't take up a lot of space, so it might not matter at all. It's just something to think about.

**Comment by trianglebutt** [comment]
I like them there.

**Comment by od0x0** [comment]
Just the data folder is enough, the rest is just bloat.  Unless we _really_ need to keep the version the same.  Because it's not like dim3 has gone through radical changes that required days and days of fixing in the past few years now, has it?

**Comment by bink** [comment]
I removed all the engine bloat and left only the data folder. I did leave it inside the game folder so people can still put their apps in there, along with readme files we might want to include.
The game folder should be what we ship when it's done.
