### ISSUE TITLE
Modular Pack - Maintenance

### ISSUE THREAD

**Issue by trianglebutt** [od0x0/7dfps#42]
maintenance_corridorWall_base
maintenance_corridorWall_insideCorner
maintenance_corridorWall_outsideCorner
maintenance_corridorWall_vent
maintenance_corridorWall_door
maintenance_corridorFloor_base
maintenance_corridorFloor_edgeStraight
maintenance_corridorFloor_edgeCorner
maintenance_corridorCeiling_base
maintenance_corridorCeiling_edgeStraight
maintenance_corridorCeiling_edgeCorner

maintenance_roomWall_base
maintenance_roomWall_insideCorner
maintenance_roomWall_outsideCorner
maintenance_roomWall_vent
maintenance_roomWall_door
maintenance_roomFloor_base
maintenance_roomFloor_edgeStraight
maintenance_roomFloor_edgeCorner
maintenance_roomCeiling_base
maintenance_roomCeiling_edgeStraight
maintenance_roomCeiling_edgeCorner

**Comment by bink** [comment]
This isn't required for the 7dpfs version, is it? I'll move it to the NaGaDeMo milestone. We can still add it later.

**Comment by trianglebutt** [comment]
This shouldn't even be open, it's not needed.
