### ISSUE TITLE
WE NEED TO DECIDE ON A SCALE TO IMPORT MAPS AT

### ISSUE THREAD

**Issue by trianglebutt** [od0x0/7dfps#59]
Okay so we need to figure out what scale we're going to import the maps from Blender into Dim3 at. It's going to be (Y, Some number). 3000 is too small so we need to agree on a scale that works for the player.

ALSO: https://github.com/Oddity007/7dfps/wiki/Map-Editing

**Comment by bink** [comment]
I've been using 4000 dim3 units per floor piece (from one corridor wall to the other) and I think it works pretty well.
What I've done is scale the pieces up in C4D to match that (though divided by ten), so every floor is 400*400 units, I then build my map, get the width of the whole map, multiply by 10 and tell dim3 to scale it to that many units on the X-axis.
Works fine, keeps proportions, looks good.

**Comment by trianglebutt** [comment]
Okay, 4000 it is then, as long as it's the same as importing Blender exports at 4000.
