### ISSUE TITLE
Script - Force Field Light Toggle

### ISSUE THREAD

**Issue by trianglebutt** [od0x0/7dfps#81]
I'd like the Force Field button to toggle off/on any lights with the same name as the force field and buttons.

**Comment by bink** [comment]
Not sure if that's possible. Dim3 has a light toggle function, but that only works for one light with one name. I'm not sure if it turns all the lights with that name off.

**Comment by trianglebutt** [comment]
I wonder if i can add a light to the forcefield model.

**Comment by bink** [comment]
You can and you did. Closed.
