### ISSUE TITLE
Concept Art - Shot Gun

### ISSUE THREAD

**Issue by trianglebutt** [od0x0/7dfps#9]
Concepts for the look of the Shot Gun weapon, as well as animation ideas.

**Comment by flagoworld** [comment]
Shotgun needs a bigger barrel than the concept illustrates.

**Comment by bink** [comment]
How much ammo does it hold? Usually a shotgun would have like 1-2 shots or something before you have to reload, right?
Maybe this one could hold more like 8, then eject all of the casings when reloading.
Imagine putting in a kind of rack or catridge with the shells on it, then firing 8 shots. Then it pops out and is switched for a new one.
Also the shotgun could have a secondary fire mode that fires all of the remaining shots at once to hit really hard, but with a lot of recoil and spread, so you gotta get real close to use it + when the casings pop out, they're hot and produce steam and smoke, and it takes a while for them to cool down so you can reload.

**Comment by flagoworld** [comment]
You'll only see 1-2 shots in super old-school or double barreled shotguns. Most these days do hold up to 8 or so down a shaft parallel to the barrel.

**Comment by trianglebutt** [comment]
Yes, it's not a single shot or anything. I was thinking about eight.

I like the secondary fire mode idea.

**Comment by trianglebutt** [comment]
Concept viewable at: Concept Art/Weapons/Shot Gun
